name: test
on: push
jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ['5.4', '5.3']
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules: true
    - uses: actboy168/setup-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - run: lua test/conformance.lua -c
    - run: lua test/benchmark.lua
